### ISSUE TITLE
Convert error 

### ISSUE THREAD

**Issue by o4dushno** [nasrat-v/chrome_engine_browser_password_stealer#1]
Hello, I have some problem:  manageprocess.cpp(35): error C2664: "int _tcsicmp(const char *,const char *)": cannot convert argument 2 from "const wchar_t *" to "const char *"

**Comment by nasrat-v** [comment]
Hi, this is because your project settings are not set to Unicode.
I've patch this for you. Try it again.
But keep in mind that today all windows application should use Unicode.

**Comment by o4dushno** [comment]
Thank you
